### ISSUE TITLE
Server started on port undefined

### ISSUE THREAD

**Issue by lexcorp** [adrianboratyn/kahoot-js#2]
[sysadmin@srvens01pro server]$ npm run devStart

> server@1.0.0 devStart /kahoot/kahoot-js/server
> nodemon server.js

[nodemon] 2.0.13
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node server.js`
Server started on port undefined
(node:32728) UnhandledPromiseRejectionWarning: MongooseError: The `uri` parameter to `openUri()` must be a string, got "undefined". Make sure the first parameter to `mongoose.connect()` or `mongoose.createConnection()` is a string.
    at NativeConnection.Connection.openUri (/kahoot/kahoot-js/server/node_modules/mongoose/lib/connection.js:684:11)
    at /kahoot/kahoot-js/server/node_modules/mongoose/lib/index.js:329:10
    at /kahoot/kahoot-js/server/node_modules/mongoose/lib/helpers/promiseOrCallback.js:32:5
    at new Promise (<anonymous>)
    at promiseOrCallback (/kahoot/kahoot-js/server/node_modules/mongoose/lib/helpers/promiseOrCallback.js:31:10)
    at Mongoose._promiseOrCallback (/kahoot/kahoot-js/server/node_modules/mongoose/lib/index.js:1150:10)
    at Mongoose.connect (/kahoot/kahoot-js/server/node_modules/mongoose/lib/index.js:328:20)
    at Object.<anonymous> (/kahoot/kahoot-js/server/server.js:20:10)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
(node:32728) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:32728) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by huzarh** [comment]
error: status code 401, net::ERR_HTTP_RESPONSE_CODE_FAILURE


Unauthorized
