### ISSUE TITLE
Auth Server started on port undefined

### ISSUE THREAD

**Issue by lexcorp** [adrianboratyn/kahoot-js#3]
[sysadmin@srvens01pro server]$ npm run devStartAuth

> server@1.0.0 devStartAuth /kahoot/kahoot-js/server
> nodemon authServer.js

[nodemon] 2.0.13
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node authServer.js`
Auth Server started on port undefined
(node:432) UnhandledPromiseRejectionWarning: MongooseError: The `uri` parameter to `openUri()` must be a string, got "undefined". Make sure the first parameter to `mongoose.connect()` or `mongoose.createConnection()` is a string.
    at NativeConnection.Connection.openUri (/kahoot/kahoot-js/server/node_modules/mongoose/lib/connection.js:684:11)
    at /kahoot/kahoot-js/server/node_modules/mongoose/lib/index.js:329:10
    at /kahoot/kahoot-js/server/node_modules/mongoose/lib/helpers/promiseOrCallback.js:32:5
    at new Promise (<anonymous>)
    at promiseOrCallback (/kahoot/kahoot-js/server/node_modules/mongoose/lib/helpers/promiseOrCallback.js:31:10)
    at Mongoose._promiseOrCallback (/kahoot/kahoot-js/server/node_modules/mongoose/lib/index.js:1150:10)
    at Mongoose.connect (/kahoot/kahoot-js/server/node_modules/mongoose/lib/index.js:328:20)
    at Object.<anonymous> (/kahoot/kahoot-js/server/authServer.js:9:10)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
(node:432) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:432) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Mhdtarek** [comment]
maybe try configuring your .env:

DATABASE_URL=string (required)
PORT=3000 (required number)
AUTH_PORT=4000 (required number)
ACCESS_TOKEN_SECRET=string (required string)
REFRESH_TOKEN_SECRET=string (required string)

**Comment by huzarh** [comment]
creat new quiz



error :        xhr.js:210          POST http://localhost:3000/api/quizes 431 (Request Header Fields Too Large)



pls  help meee

**Comment by Mhdtarek** [comment]
When will be fixed?
